apiVersion: v1
kind: Namespace
metadata:
  name: deliverymanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliverymanager
  namespace: deliverymanager
  labels:
    app: deliverymanager
spec:
  selector:
    matchLabels:
      app: deliverymanager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deliverymanager
    spec:
      containers:
      - image: 566034038752.dkr.ecr.us-west-2.amazonaws.com/sykang/deliverymanager:latest
        imagePullPolicy: Always
        name: deliverymanager
        ports:
        - containerPort: 80
          protocol: TCP
---          
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: deliverymanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deliverymanager
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 99
